app:
    pattern:  /
    defaults: { _controller: SimplyTestableWebClientBundle:App:index }

app_progress:
    pattern:  /{website}/{test_id}/progress/
    defaults: { _controller: SimplyTestableWebClientBundle:App:progress }  
    requirements:
        website: ".+" 
        
app_tasks:
    pattern:  /{website}/{test_id}/tasks/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:collection, _format: json }  
    requirements:
        website: ".+"   
        
app_task_ids:
    pattern:  /{website}/{test_id}/tasks/ids/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:idCollection, _format: json }  
    requirements:
        website: ".+"           
        
app_task_results:
    pattern:  /{website}/{test_id}/{task_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:results }  
    requirements:
        website: ".+"          
        
app_task_results_collection:
    pattern:  /{website}/{test_id}/{task_ids}/results/collection/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:resultsCollection, _format: json }  
    requirements:
        website: ".+"          
        
app_results:
    pattern:  /{website}/{test_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:App:results }  
    requirements:
        website: ".+"      

test_start:
    pattern:  /test/start/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:start }
    
test_cancel:
    pattern:  /test/{website}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:cancel }  
    requirements:
        website: ".+"
        
app_test:
    pattern:  /{website}/{test_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:App:testCurrent }  
    requirements:
        website: ".+"        
        
outdated_browser:
    pattern:  /outdated-browser/
    defaults: { _controller: SimplyTestableWebClientBundle:App:outdatedBrowser }            